#######################################
# NGINX Servers (WebServ NPMP)

  nginx01:
    image: nginx:latest
    container_name: Web-Serv1
    restart: always
    tty: true
    ports:
      - 60101:80
    volumes:
      - ./volumes/WebServ/nginx01/www/html/:/var/www/html/nginx01
      - ./volumes/WebServ/nginx01/config/conf.d/:/etc/nginx/conf.d
    links:
      - php-fpm8
    depends_on:
      - php-fpm8

  nginx02:
    image: nginx:latest
    container_name: Web-Serv2
    restart: always
    tty: true
    ports:
      - 60102:80
    volumes:
      - ./volumes/WebServ/nginx02/www/html/:/var/www/html/nginx02
      - ./volumes/WebServ/nginx02/config/conf.d/:/etc/nginx/conf.d
    links:
      - php-fpm8
    depends_on:
      - php-fpm8

# PHP8 FPN (WebServ NPMP)

  php-fpm8:
    image: php:8.2-fpm
    container_name: PHP-8-FPM
    restart: always
    volumes:
      - ./volumes/WebServ/nginx01/www/html/:/var/www/html/nginx01
      - ./volumes/WebServ/nginx02/www/html/:/var/www/html/nginx02

# MariaDB (WebServ NPMP)

  mariadb:
    image: linuxserver/mariadb
    container_name: MariaDB
    restart: always
    environment:
      - TZ=UTC
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
      - MYSQL_USER=lmds # This user will have superuser access to the database
      - MYSQL_ROOT_PASSWORD=passw0rd # Set this to root password for installation (minimum 4 characters).
      - MYSQL_PASSWORD=passw0rd # Set this to the password you want to use for you MYSQL_USER (minimum 4 characters).
      - MYSQL_DATABASE=lmdsdb # Specify the name of a database to be created on image startup.
    volumes:
      - ./volumes/mariadb:/config # Contains the db itself and all assorted settings.
    ports:
      - 3306:3306/tcp # MariaDB listens on this port

# PHP MyAdmin (WebServ NPMP)

  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    restart: always
    environment:
      - TZ=UTC # Specify a timezone to use
      - PUID=1000 # User ID to run as
      - PGID=1000 # Group ID to run as
      - PMA_ARBITRARY=1 # Set to 1 to allow you to connect to any server. Setting to 0 will only allow you to connect to specified hosts
    volumes:
      - ./volumes/phpmyadmin:/config # Contains all relevant configuration files.
    ports:
      - 8888:80/tcp # Web UI
    depends_on:
      - mariadb